### ISSUE TITLE
SystemCommandのReloadCommandを実行した際にアプリケーションが落ちる不具合

### ISSUE THREAD

**Issue by uluvtu** [syoriken-ob/DiSpeakBouyomiChanBridge.NET#31]

**Comment by BWater09** [comment]
なんか直ってるっぽい？

**Comment by uluvtu** [comment]
@BWater09 
落ちなくはなったけど他のサービスが再起動されずにのこるっぽい
VBAN系とか
それはまた別Issueか

**Comment by BWater09** [comment]
[vfixInitializeCommandError](https://github.com/syoriken-ob/DiSpeakBouyomiChanBridge.NET/releases/tag/vfixInitializeCommandError)
にて修正済み
